name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. This step downloads your code into the runner
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Now you can make gradlew executable
      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
